### ISSUE TITLE
Tooltip pops up by itself, over other top-level applications, even when app is minimized or the mouse not hovering over the control.

### ISSUE THREAD

**Issue by DexterLagan** [alex-hhh/gui-widget-mixins#2] opened 2020-10-21 12:59 UTC
I wrote this generic procedure to add a button. It works great, however the tooltip pops up by itself (even when the app is minimized).

;; generate a standard or quarter-size button. Label can be a bitmap
(define (make-button parent label config small? button-size font-size license-dest-path tooltip-text) 
  (new (tooltip-mixin button%)
       [label label]
       [parent parent]
       [min-width button-size]
       [stretchable-width button-size]
       [min-height (if small? 24 button-size)]
       [stretchable-height (if small? #f button-size)]
       [font (make-object font% font-size 'swiss 'normal 'bold)]
       [tooltip tooltip-text]
       [callback (λ (b e) (button-callback label config license-dest-path))]))

**Comment by alex-hhh** [comment] 2020-10-21 22:30
Hi Dexter,

Thanks for reporting this issue.  It looks similar to issue #1 where mouse events were delivered to the GUI widget differently on different platforms.   To further investigate this issue, can you please:

* provide a complete sample program illustrating the problem (the code that you provided does not run, because it has other dependencies)
* provide the OS you are using
* provide a more detailed list of steps to reproduce the problem (i.e. do you hover with the mouse over the button to trigger the tooltip, than minimieze the application and the tooltip remains on?)

Thanks,
Alex.

**Comment by DexterLagan** [comment] 2020-10-22 13:20
Here's a minimum program to reproduce the problem :
---
#lang racket/gui
(require gui-widget-mixins)

;;; defs

;; generates a small frame to fill with controls
(define (make-elastic-frame appname)
  (new (class frame% (super-new)
         (define/augment (on-close)
           (exit 0)))
       [label appname]
       [width 0]
       [height 0]
       [stretchable-width 1024]
       [stretchable-height #f]))

(define my-frame
  (make-elastic-frame "my app"))

;; create a button with tooltip
(define my-button
  (new (tooltip-mixin button%)
       [label "Button"]
       [parent my-frame]
       [min-width 200]
       [stretchable-width 200]
       [min-height 50]
       [stretchable-height 100]
       [tooltip "tooltip-text"]
       [callback (λ (b e) (void))]))

;;; main

(send my-frame show #t)

---
  Leaving that small window with one button open, the tooltip appears randomly over other apps. I'm still trying to find what triggers the issue, because it does not appear on every app.

**Comment by DexterLagan** [comment] 2020-10-22 13:22
Also, I'm running these on Windows 10 Pro, build 1909. The problem does not seem to happen on build 2004.

**Comment by DexterLagan** [comment] 2020-10-22 13:24
Also, using Racket 7.8, with the latest gui-widget-mixins package.

**Comment by alex-hhh** [comment] 2020-10-22 13:30
Thanks for providing the sample program -- I can reproduce the problem and I will look into fixing it over the weekend.

**Comment by alex-hhh** [comment] 2020-10-24 23:47
I have pushed a repair for this issue -- it seems that Windows does not send "mouse leave" events, so the code did not know that the mouse moved elsewhere.  Can you please update the package and check if this fixes the problem for you?

**Comment by DexterLagan** [comment] 2020-10-25 07:47
Sounds good, thanks! I’ll give it a try and report back.

Dex

________________________________

**Comment by alex-hhh** [comment] 2020-11-02 00:46
I will close this issue now.  If you notice any problems, mention it here and I will re-open it.

**Closed as completed by alex-hhh** 2020-11-02 00:46 UTC

**Comment by DexterLagan** [comment] 2020-11-02 06:57
Sounds good. I put an app into production last week and haven’t heard back. I’ll let you know if anybody notices the problem again. Thanks!

Dex

________________________________
